### ISSUE TITLE
《Git超级简明手册》裡的历史不对

### ISSUE THREAD

**Issue by nnkken** [shendlcode/blog#1]
《Git超级简明手册》裡写：

> Git----免费的分布式版本控制系统。在Mercurial不再免费提供给linux项目使用后开发。」

Linux项目在Git之前用的是BitKeeper，一个商业软件。
在BitKeeper不再免费提供后，Linux开发者们开始著手开发代替品，一个是Git，另一个就是Mercurial。
两者和BitKeeper一样，都是分布式版本控制系统，而且都是免费、开源的。

**Comment by shendlcode** [comment]
Thanks！已经修复了。
